name: First workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world!"
      - name: n commands
        run: |
            echo "premeire ligne"
            echo "seconde ligne"
      - name: Print goodbye
        run: echo "salut" 
       
